environment:
  matrix:
    - ANDROID_SDK_ROOT: "C:\\android-sdk-windows"
install:
  - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-3859397.zip
  - 7z x sdk-tools-windows-3859397.zip -oC:\android-sdk-windows > nul
  - yes | C:\android-sdk-windows\tools\bin\sdkmanager.bat --licenses
build_script:
  - gradlew.bat assemble
test_script:
  - gradlew.bat test
