name: Android CI

on:
  push:
    branches: [ master, main, dex, google-maps, github-ci ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          #distribution: 'adopt'
          distribution: 'temurin'
          #distribution: 'zulu'
          #cache: gradle

      - name: Create properties file with empty API key
        run: echo MAPS_API_KEY=a >> local.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          target: default #, google_apis
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace
